export class FirstModel {

  public _id!: string; // generated by mongoDB
  public fname!: string;
  public lname!: string;
  public eso!: string;
  public availability!: string;
  public company!: string;
  public armed!: string;
  public note!: string;
  public previousService!: string;
  //public where!: string;
  public createdAt!: Date; // generated by mongoDB
  constructor(model?: any) {
    Object.assign(this, model);
  }
}

