export class IpiresiesModel {

  public _id!: string; // generated by mongoDB
  public serviceName!: string;
  public numOfSoldiers!: number;
  public untilNow!: number;
  //public where!: string;
  public createdAt!: Date; // generated by mongoDB
  constructor(model?: any) {
    Object.assign(this, model);
  }
}

